import type { AnalystCapabilityPackage } from '../types';

export const ANALYST_CAPABILITY_SKILLS = [
    {
        id: 'analyst.skill.data_quality_verification',
        kind: 'skill',
        label: 'Data Quality Verification',
        intent: 'Verify dataset cleanliness and explain concrete data quality risks before deeper analysis.',
        description: 'Reusable analyst skill for null-rate, duplicate, schema, and deterministic cleanliness checks.',
        allowedToolNames: ['data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'column_quality_snapshot', 'dataset_knowledge', 'visible_evidence'],
        completionChecks: [
            'State whether a material data quality issue is grounded in visible evidence or a read-only check.',
            'Do not create or review charts while the request is still about dataset cleanliness.',
        ],
        overrideTaskMode: 'inspect',
        overrideExpectedOutcome: 'answer',
        preferredFallback: 'answer',
    },
    {
        id: 'analyst.skill.duckdb_validation_query',
        kind: 'skill',
        label: 'DuckDB Validation Query',
        intent: 'Answer read-only validation requests through one bounded structured DuckDB-compatible query.',
        description: 'Reusable analyst skill for counts, grouped checks, duplicate scans, and validation-style lookups.',
        allowedToolNames: ['data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['analysis_intent_brief', 'dataset_columns', 'query_trace', 'visible_evidence'],
        completionChecks: [
            'Use one structured read-only query or clarify the unstable scope.',
            'Summarize the grounded result without escalating into chart creation unless the user explicitly asks next.',
        ],
        overrideTaskMode: 'inspect',
        overrideExpectedOutcome: 'table',
        preferredFallback: 'answer',
    },
    {
        id: 'analyst.skill.chart_recommendation_review',
        kind: 'skill',
        label: 'Chart Recommendation Review',
        intent: 'Review an existing card or chart recommendation and suggest the smallest grounded follow-up.',
        description: 'Reusable analyst skill for checking chart fit, fallback charts, and card-level recommendation quality.',
        allowedToolNames: ['card.review', 'ui.change_chart_type', 'ui.show_card_data', 'conversation.request_clarification'],
        requiredContext: ['card_context', 'query_trace', 'visible_evidence'],
        completionChecks: [
            'Ground every recommendation in an existing card, chart summary, or visible result.',
            'Prefer review or chart-type refinement before proposing a new chart from scratch.',
        ],
        overrideTaskMode: 'visualize',
        overrideExpectedOutcome: 'card',
        preferredFallback: 'answer',
    },
    {
        id: 'analyst.skill.pivot_matrix_analysis',
        kind: 'skill',
        label: 'Pivot Matrix Analysis',
        intent: 'Answer matrix, crosstab, and pivot-style requests with a read-only pivot artifact.',
        description: 'Reusable analyst skill for two-axis summaries that should stay as analysis output rather than dataset mutation.',
        allowedToolNames: ['analysis.pivot_matrix', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return a read-only pivot artifact or one concise clarification about unstable row, column, or metric scope.',
            'Do not use data.mutate to create a permanent pivoted dataset for this class of request.',
        ],
        overrideTaskMode: 'pivot_matrix',
        overrideExpectedOutcome: 'card',
        preferredFallback: 'clarify',
    },
    {
        id: 'analyst.skill.period_compare_analysis',
        kind: 'skill',
        label: 'Period Compare Analysis',
        intent: 'Answer period-over-period comparison requests with grounded current, previous, and variance outputs.',
        description: 'Reusable analyst skill for MoM, QoQ, YoY, WoW, variance, and variance percentage workflows.',
        allowedToolNames: ['analysis.period_compare', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Require a stable date column and grain before comparing periods.',
            'Return current, previous, variance, and variance percentage instead of a generic chart-only response.',
        ],
        overrideTaskMode: 'period_compare',
        overrideExpectedOutcome: 'card',
        preferredFallback: 'clarify',
    },
    {
        id: 'analyst.skill.cohort_retention_analysis',
        kind: 'skill',
        label: 'Cohort Retention Analysis',
        intent: 'Answer retention, churn, and new-user cohort requests through a catalog-backed cohort workflow.',
        description: 'Reusable analyst skill for retention-style analysis that requires explicit signup, activity, and user identifiers.',
        allowedToolNames: ['analysis.cohort_retention', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Use the metric catalog and return a structured blocker when required fields are missing.',
            'Prefer a matrix/data-table-first cohort result instead of an improvised chart.',
        ],
        overrideTaskMode: 'cohort_retention',
        overrideExpectedOutcome: 'card',
        preferredFallback: 'clarify',
    },
    {
        id: 'analyst.skill.root_cause_breakdown',
        kind: 'skill',
        label: 'Root Cause Breakdown',
        intent: 'Explain which segments or dimensions drove a metric change between two periods.',
        description: 'Reusable analyst skill for driver analysis, contributor rankings, and variance decomposition.',
        allowedToolNames: ['analysis.root_cause_breakdown', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return contributor rows with current, previous, and contribution values.',
            'Do not collapse a driver-analysis request into a generic period chart.',
        ],
        overrideTaskMode: 'root_cause_breakdown',
        overrideExpectedOutcome: 'card',
        preferredFallback: 'clarify',
    },
    {
        id: 'analyst.skill.bounded_statistical_analysis',
        kind: 'skill',
        label: 'Bounded Statistical Analysis',
        intent: 'Answer supported statistical requests through bounded analysis contracts only.',
        description: 'Reusable analyst skill for correlation, regression, distribution, outlier scans, and simple trend analysis.',
        allowedToolNames: ['analysis.correlation', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Require explicit columns and minimum sample support before running a statistical tool.',
            'Return a bounded analysis result or a structured blocker instead of free-form statistical speculation.',
        ],
        overrideTaskMode: 'statistical_analysis',
        overrideExpectedOutcome: 'card',
        preferredFallback: 'clarify',
    },
    {
        id: 'analyst.skill.answer_scalar_question',
        kind: 'skill',
        label: 'Scalar Question Answer',
        intent: 'Answer a single-entity, single-metric question with a direct scalar value.',
        description: 'Reusable analyst skill for questions like "What is the total sales for X?" that expect a numeric or text answer, not a chart.',
        allowedToolNames: ['data.query', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return a direct scalar answer from one bounded query.',
            'Do not escalate into chart creation or plan generation unless the user explicitly requests a visual.',
        ],
        overrideTaskMode: 'inspect',
        overrideExpectedOutcome: 'answer',
        preferredFallback: 'answer',
    },
] as const satisfies readonly AnalystCapabilityPackage[];

export const ANALYST_CAPABILITY_RECIPES = [
    {
        id: 'analyst.recipe.dataset_quality_triage',
        kind: 'recipe',
        label: 'Dataset Quality Triage',
        intent: 'Package a repeatable cleanliness triage workflow for analyst follow-up chat turns.',
        description: 'Combines the data quality verification skill with bounded read-only inspection tools and explicit completion checks.',
        allowedToolNames: ['data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'column_quality_snapshot', 'dataset_knowledge', 'visible_evidence'],
        completionChecks: [
            'Inspect or explain quality issues with deterministic evidence.',
            'Hand control back once the quality verdict and next cleanup step are explicit.',
        ],
    },
    {
        id: 'analyst.recipe.read_only_duckdb_validation',
        kind: 'recipe',
        label: 'Read-Only DuckDB Validation',
        intent: 'Package a reproducible validation workflow for grouped checks and row lookups.',
        description: 'Combines the DuckDB validation query skill with read-only tool exposure and validation-first completion checks.',
        allowedToolNames: ['data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['analysis_intent_brief', 'dataset_columns', 'query_trace', 'visible_evidence'],
        completionChecks: [
            'Stay inside structured read-only inspection.',
            'Return a grounded answer or one concise clarification instead of branching into plan generation.',
        ],
    },
    {
        id: 'analyst.recipe.chart_review_followup',
        kind: 'recipe',
        label: 'Chart Review Follow-Up',
        intent: 'Package a repeatable review workflow for existing card recommendations.',
        description: 'Combines the chart recommendation review skill with review-first tool exposure for card follow-up turns.',
        allowedToolNames: ['card.review', 'ui.change_chart_type', 'ui.show_card_data', 'conversation.request_clarification'],
        requiredContext: ['card_context', 'query_trace', 'visible_evidence'],
        completionChecks: [
            'Review the existing card before creating new analysis work.',
            'Recommend the smallest grounded change that improves the chart or explain why it is already acceptable.',
        ],
    },
    {
        id: 'analyst.recipe.read_only_pivot_matrix',
        kind: 'recipe',
        label: 'Read-Only Pivot Matrix',
        intent: 'Package a repeatable pivot workflow for read-only matrix outputs.',
        description: 'Combines pivot-matrix analysis with clarification-first handling for unstable dimensions or metrics.',
        allowedToolNames: ['analysis.pivot_matrix', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return a pivot artifact grounded in the current dataset.',
            'Keep the result read-only and hand back a stable matrix/table output.',
        ],
    },
    {
        id: 'analyst.recipe.period_compare_variance',
        kind: 'recipe',
        label: 'Period Compare Variance',
        intent: 'Package a reproducible period comparison workflow for variance analysis.',
        description: 'Combines period-compare analysis with date/grain clarification and variance-first completion checks.',
        allowedToolNames: ['analysis.period_compare', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return a current-versus-previous comparison with variance metrics.',
            'Clarify date column or grain instead of silently guessing them when unstable.',
        ],
    },
    {
        id: 'analyst.recipe.catalog_backed_cohort_analysis',
        kind: 'recipe',
        label: 'Catalog-Backed Cohort Analysis',
        intent: 'Package a metric-catalog-driven workflow for retention, churn, and new-user analysis.',
        description: 'Combines cohort analysis with catalog-backed field resolution and structured blocking behavior.',
        allowedToolNames: ['analysis.cohort_retention', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Resolve required fields through the metric catalog before running the cohort tool.',
            'Return a cohort matrix or a deterministic missing-field blocker.',
        ],
    },
    {
        id: 'analyst.recipe.root_cause_driver_breakdown',
        kind: 'recipe',
        label: 'Root Cause Driver Breakdown',
        intent: 'Package a repeatable driver-analysis workflow for variance decomposition.',
        description: 'Combines root-cause breakdown analysis with contributor-ranking completion checks.',
        allowedToolNames: ['analysis.root_cause_breakdown', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return ranked contributors and contribution values.',
            'Keep the answer focused on explaining change drivers rather than broad exploratory charts.',
        ],
    },
    {
        id: 'analyst.recipe.bounded_statistical_followup',
        kind: 'recipe',
        label: 'Bounded Statistical Follow-Up',
        intent: 'Package a bounded statistical workflow for supported column-level analyses.',
        description: 'Combines bounded statistical analysis with explicit minimum-input and failure-handling checks.',
        allowedToolNames: ['analysis.correlation', 'data.query', 'spreadsheet.filter', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Stay inside the supported statistical tool contract.',
            'Return a statistical artifact or a structured blocker for insufficient data.',
        ],
    },
    {
        id: 'analyst.recipe.scalar_question_answer',
        kind: 'recipe',
        label: 'Scalar Question Answer',
        intent: 'Package a direct-answer workflow for single-entity, single-metric questions.',
        description: 'Combines scalar question answering with a single bounded query and direct text response.',
        allowedToolNames: ['data.query', 'conversation.request_clarification'],
        requiredContext: ['dataset_columns', 'analysis_intent_brief', 'visible_evidence'],
        completionChecks: [
            'Return a direct scalar answer from one bounded query.',
            'Do not escalate into chart creation unless explicitly requested.',
        ],
    },
] as const satisfies readonly AnalystCapabilityPackage[];

export const getAnalystCapabilitySkill = (id: string) =>
    ANALYST_CAPABILITY_SKILLS.find(skill => skill.id === id) ?? null;

export const getAnalystCapabilityRecipe = (id: string) =>
    ANALYST_CAPABILITY_RECIPES.find(recipe => recipe.id === id) ?? null;
