/* eslint-disable no-undef */

const ensureGlobal = (name, fallback = null) => {
  if (typeof window !== 'undefined' && window[name]) {
    return window[name];
  }
  return fallback;
};

const htmlToImage = ensureGlobal('htmlToImage');
const Papa = ensureGlobal('Papa');

export const exportToPng = async (element, title) => {
  if (!element || !htmlToImage) {
    throw new Error('PNG export is unavailable in this environment.');
  }

  const safeTitle = String(title || 'analysis-card').replace(/\s+/g, '_');
  const dataUrl = await htmlToImage.toPng(element, {
    backgroundColor: '#ffffff',
    pixelRatio: 2,
  });
  const link = document.createElement('a');
  link.download = `${safeTitle}.png`;
  link.href = dataUrl;
  link.click();
};

export const exportToCsv = (rows, title) => {
  if (!Array.isArray(rows) || !rows.length) {
    throw new Error('No data available for CSV export.');
  }
  if (!Papa) {
    throw new Error('PapaParse is unavailable for CSV export.');
  }
  const safeTitle = String(title || 'analysis-card').replace(/\s+/g, '_');
  const csv = Papa.unparse(rows);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.setAttribute('download', `${safeTitle}.csv`);
  link.click();
};

export const exportToHtml = async (element, title, rows, summaryText) => {
  if (!element) {
    throw new Error('HTML export requires a rendered card element.');
  }
  if (!Array.isArray(rows) || !rows.length) {
    throw new Error('No data available for HTML export.');
  }

  const chartCanvas = element.querySelector('canvas');
  if (!chartCanvas) {
    throw new Error('Chart canvas not found for export.');
  }

  const chartImage = chartCanvas.toDataURL('image/png');
  const headers = Object.keys(rows[0] || {});
  const dataTableHtml = `
    <table border="1" style="border-collapse:collapse;width:100%;font-family:sans-serif;color:#333;">
      <thead>
        <tr style="background-color:#f2f2f2;">
          ${headers.map(header => `<th style="padding:8px;">${header}</th>`).join('')}
        </tr>
      </thead>
      <tbody>
        ${rows
          .map(
            row => `<tr>${headers
              .map(header => `<td style="padding:8px;">${row[header] ?? ''}</td>`)
              .join('')}</tr>`
          )
          .join('')}
      </tbody>
    </table>
  `;

  const safeTitle = String(title || 'analysis-card').trim();
  const normalisedTitle = safeTitle.replace(/\s+/g, '_');
  const summaryHtml = String(summaryText || '')
    .replace(/\n/g, '<br>')
    .replace(/---/g, '<hr>');

  const html = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${safeTitle}</title>
    <style>
      body { font-family: sans-serif; line-height: 1.6; padding: 24px; color: #111827; }
      h1, h2 { margin-bottom: 12px; }
      .card { border: 1px solid #e5e7eb; padding: 20px; border-radius: 8px; margin-bottom: 24px; background: #ffffff; }
      img { max-width: 100%; border: 1px solid #e5e7eb; border-radius: 6px; }
      table { margin-top: 12px; }
    </style>
  </head>
  <body>
    <h1>Analysis Report: ${safeTitle}</h1>
    <div class="card">
      <h2>Chart</h2>
      <img src="${chartImage}" alt="Chart for ${safeTitle}" />
    </div>
    <div class="card">
      <h2>AI Summary</h2>
      <p>${summaryHtml}</p>
    </div>
    <div class="card">
      <h2>Data</h2>
      ${dataTableHtml}
    </div>
    <p style="font-size:0.8rem;color:#6b7280;">Generated by CSV Data Analysis Agent on ${new Date().toLocaleString()}</p>
  </body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.setAttribute('download', `Report_${normalisedTitle}.html`);
  link.click();
};
