import type { ToolManifest } from '../../../../types';
import { cardRefineSchema, emptyObjectSchema, suggestionActionSchema } from '../toolManifestSchemas';
import {
    requireAnalysisCards,
    requireCleaningRun,
    validateCardRefine,
    validateSuggestionId,
} from '../toolManifestSupport';

export const createRuntimeToolManifests = (): ToolManifest[] => [
    {
        name: 'cleaning.resume',
        description: 'Resume the current cleaning runtime.',
        category: 'conversation',
        risk: 'medium',
        enabledByDefault: true,
        inputSchema: emptyObjectSchema,
        groups: ['cleaning.edit'],
        promptHints: ['Use when the user asks to continue an existing cleaning run.'],
        resultShape: 'Resumes the paused cleaning runtime.',
        isAvailable: requireCleaningRun,
    },
    {
        name: 'cleaning.restart',
        description: 'Restart the current cleaning runtime from the raw dataset.',
        category: 'conversation',
        risk: 'medium',
        enabledByDefault: true,
        inputSchema: emptyObjectSchema,
        groups: ['cleaning.edit'],
        promptHints: ['Use when the user explicitly asks to restart cleaning from the beginning.'],
        resultShape: 'Restarts the cleaning runtime from raw.csv.',
        isAvailable: requireCleaningRun,
    },
    {
        name: 'card.refine',
        description: 'Modify parameters of an existing analysis card: change chart type, adjust topN limit, apply or clear a filter, toggle data table visibility, or rewrite the AI summary.',
        category: 'card',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: cardRefineSchema,
        groups: ['card.mutate'],
        promptHints: [
            'Use when the user asks to change how an existing card looks, is filtered, or has its summary rewritten (e.g., "change to line chart", "top 5", "filter to Region = North", "rewrite the summary", "update summary to focus on trends").',
            'Always reference a valid cardId from the current card list. When the user @mentions a card, use that cardId.',
            'Include only the changes that need to be applied — omit unchanged fields.',
            'To clear a filter, pass filter with an empty values array.',
            'To rewrite or update the card summary text, pass changes.summary as a plain text string. ALWAYS use card.refine for summary rewrite requests — do NOT reply with text instead.',
        ],
        resultShape: 'Applies the requested parameter changes to the specified card in-place.',
        isAvailable: requireAnalysisCards,
        validate: (args, context) => validateCardRefine(args as Record<string, any>, context),
    },
    {
        name: 'card.suggestion.apply',
        description: 'Apply one active card enhancement suggestion.',
        category: 'card',
        risk: 'medium',
        enabledByDefault: true,
        inputSchema: suggestionActionSchema,
        groups: ['card.mutate'],
        promptHints: ['Use when the user asks to approve or apply a specific suggestion.'],
        resultShape: 'Applies one active card enhancement suggestion.',
        isAvailable: requireAnalysisCards,
        validate: (args, context) => validateSuggestionId(args?.suggestionId, context),
    },
    {
        name: 'card.suggestion.dismiss',
        description: 'Dismiss one active card enhancement suggestion.',
        category: 'card',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: suggestionActionSchema,
        groups: ['card.mutate'],
        promptHints: ['Use when the user asks to dismiss or skip a specific suggestion.'],
        resultShape: 'Dismisses one active card enhancement suggestion.',
        isAvailable: requireAnalysisCards,
        validate: (args, context) => validateSuggestionId(args?.suggestionId, context),
    },
];
