import type { ToolManifest } from '../../../../types';
import {
    workspaceDiffSchema,
    workspaceHeadSchema,
    workspaceListSchema,
    workspacePathSchema,
    workspaceReplaceSchema,
    workspaceSearchSchema,
    workspaceWriteSchema,
} from '../toolManifestSchemas';
import { requireDataset, validateWorkspacePayload } from '../toolManifestSupport';

export const createWorkspaceToolManifests = (): ToolManifest[] => [
    {
        name: 'workspace.list',
        description: 'List bounded workspace files.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: workspaceListSchema,
        groups: ['workspace.inspect'],
        promptHints: ['Use for deterministic workspace inspection only.'],
        resultShape: 'Returns a bounded file listing.',
        capabilities: { readOnly: true, agrunReadOnlyCanary: true },
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('list', args ?? {}),
    },
    {
        name: 'workspace.tree',
        description: 'Return a tree view of the virtual workspace.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: { type: 'object', properties: { path: { type: 'string' } } },
        groups: ['workspace.inspect', 'workspace.inspect.tree', 'cleaning.inspect'],
        promptHints: ['Use this before reading files when you need workspace structure.'],
        resultShape: 'Returns a tree of virtual workspace paths.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('tree', args ?? {}),
    },
    {
        name: 'workspace.read',
        description: 'Read one bounded workspace file.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: workspacePathSchema,
        groups: ['workspace.inspect', 'cleaning.inspect', 'cleaning.verify'],
        promptHints: ['Only use readable workspace or dataset paths.'],
        resultShape: 'Returns file contents.',
        capabilities: { readOnly: true, agrunReadOnlyCanary: true },
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('read', args ?? {}),
    },
    {
        name: 'workspace.search',
        description: 'Search bounded workspace files by text query.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: workspaceSearchSchema,
        groups: ['workspace.inspect', 'cleaning.inspect', 'cleaning.verify'],
        promptHints: ['Use for deterministic file inspection, not arbitrary filesystem search.'],
        resultShape: 'Returns matching workspace paths.',
        capabilities: { readOnly: true, agrunReadOnlyCanary: true },
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('search', args ?? {}),
    },
    {
        name: 'workspace.grep',
        description: 'Search bounded workspace files and return path, line, and snippet matches.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: workspaceSearchSchema,
        groups: ['workspace.inspect', 'cleaning.inspect', 'cleaning.verify'],
        promptHints: ['Prefer this over workspace.search when you need line-level evidence.'],
        resultShape: 'Returns matching files with line numbers and snippets.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('grep', args ?? {}),
    },
    {
        name: 'workspace.head',
        description: 'Read the first N lines of a bounded workspace file.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: workspaceHeadSchema,
        groups: ['workspace.inspect', 'cleaning.inspect', 'cleaning.verify'],
        promptHints: ['Use this for quick CSV inspection without loading the whole file.'],
        resultShape: 'Returns the first lines of one file.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('head', args ?? {}),
    },
    {
        name: 'workspace.diff',
        description: 'Show a compact diff between two virtual workspace files.',
        category: 'workspace',
        risk: 'low',
        enabledByDefault: true,
        inputSchema: workspaceDiffSchema,
        groups: ['workspace.inspect', 'workspace.inspect.diff'],
        promptHints: ['Use this to compare raw.csv vs cleaned.csv or inspect edit impact.'],
        resultShape: 'Returns line-level differences between two files.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('diff', args ?? {}),
    },
    {
        name: 'workspace.replace',
        description: 'Replace text inside a writable workspace file.',
        category: 'workspace',
        risk: 'high',
        enabledByDefault: true,
        inputSchema: workspaceReplaceSchema,
        groups: ['workspace.edit'],
        promptHints: ['Keep rewritten cleaned files valid JSON or CSV.'],
        resultShape: 'Mutates one writable workspace file.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('replace', args ?? {}),
    },
    {
        name: 'workspace.write',
        description: 'Overwrite a writable workspace file.',
        category: 'workspace',
        risk: 'high',
        enabledByDefault: true,
        inputSchema: workspaceWriteSchema,
        groups: ['workspace.edit'],
        promptHints: ['Only target writable workspace or cleaned dataset files.'],
        resultShape: 'Writes file content.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('write', args ?? {}),
    },
    {
        name: 'workspace.append',
        description: 'Append text to a writable workspace file.',
        category: 'workspace',
        risk: 'high',
        enabledByDefault: true,
        inputSchema: workspaceWriteSchema,
        groups: ['workspace.edit'],
        promptHints: ['Use only when appending keeps the target file valid.'],
        resultShape: 'Appends file content.',
        isAvailable: requireDataset,
        validate: args => validateWorkspacePayload('append', args ?? {}),
    },
];
